### ISSUE TITLE
TensorBoard Opens to unreacheachable WebPage

### ISSUE THREAD

**Issue by etfong** [Microsoft/vs-tools-for-ai#4] opened 2018-01-02 21:58 UTC
Webpage is unreachable when running TensorBoard (http://127.0.0.1:1025)

**Comment by linmajia** [comment] 2018-01-03 07:14
Hi etfong,

Thanks for your feedback! I guess that your TensorBoard log files are not on drive C.

When creating a TensorBoard process, we pass the full path of the log directory to TensorBoard. However, TensorBoard uses a colon as a separator between the optional "run name" and the path in the --logdir argument. So if your log directory is e.g. "d:\log", then TensorBoard will interpret this string as two parts due to the ":". The run name is "d", and the log directory is "\log". Since TensorBoard is launched from VS, the drive letter of the default working directory is "C" and then TensorBoard cannot find log files.

As a workaround, please put your projects and log files on drive C. We will fix the issue soon.

**Comment by linmajia** [comment] 2018-03-14 05:51
Fixed in version 0.3.3.0.

Thanks.

**Closed by linmajia** 2018-03-14 05:51 UTC

**Comment by XUEZIJIAN** [comment] 2018-07-31 14:13
I have the same problem.(http://msi:1025)
And put the projects and log files on drive C does not work.
AI Tools 0.4.1.664470
Visual Studio 2017 15.7.5

**Comment by linmajia** [comment] 2018-08-01 13:30
@XUEZIJIAN , thank you very much for the feedback.

Did you see a TensorBoard process is launched? Which version of TensorFlow are you using? I suggest that you install TensorFlow 1.5.0 on Windows and try it again.

Thanks.

**Comment by XUEZIJIAN** [comment] 2018-08-03 16:41
@linmajia ,
Sorry to reply late. 
I use tensorflow1.6. Actually it works fine two month ago(by right click in Visual Studio).
The process is just flashed. I can't see the content. After about 10s, the browser will open automatically.(msi:1025/)
And I don't know how to use cmd in VS. But I tried several:

PS D:\> python -m tensorboard --logdir=logs/
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\python.exe: No module named tensorboard.__main__; 'tensorboard' is a package and cannot be directly executed

PS D:\> tensorboard --logdir=logs/
Fatal error in launcher: Unable to create process using '""c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\python.exe"  "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\Scripts\tensorboard.exe" --logdir=logs/'

PS D:\> python -m tensorflow.tensorboard --logdir=logs/
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\python.exe: No module named tensorflow.tensorboard

Thank you very much.

**Comment by linmajia** [comment] 2018-08-06 05:59
@XUEZIJIAN , thanks for the runtime information.

It seems that you are using Anaconda shipped with VS 2017. Did you install other Python environments too? First, you need to confirm that TensorFlow 1.6 and TensorBoard 1.6 are really installed within this Anaconda environment. Then, you open a CMD terminal and run: "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\Scripts\tensorboard.exe" --logdir=logs/ "

**Comment by XUEZIJIAN** [comment] 2018-08-08 00:09
@linmajia 
Thank you very much for your patience.
They're in the same environment. but the tensorboard is 1.10 now.

here's the result
C:\Users\XZJ> "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\Scripts\tensorboard.exe" --logdir=D:/logs
Fatal error in launcher: Unable to create process using '""c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\python.exe"  "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\Scripts\tensorboard.exe" --logdir=D:/logs'

It looks like still I didn't use CMD correctly? Vs can get a address  at least.

**Comment by linmajia** [comment] 2018-08-08 05:41
@XUEZIJIAN , did you install TensorFlow/TensorBoard directly into the Anaconda master environment? Seems that TensorFlow/TensorBoard are broken. I suggest that you uninstall and then reinstall them:
1. Open a CMD terminal with Administrative permission.
2. "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\python.exe" -m pip uninstall -y -q tensorboard tensorflow
3. "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\python.exe" -m pip install tensorflow==1.6

If you have NVidia GPU, you can replace "tensorflow" with "tensorflow-gpu" to install the GPU version.

**Comment by XUEZIJIAN** [comment] 2018-08-08 06:49
@linmajia ,yes and I just reinstalled them according to your guidance.
Now I have tensorflow-gpu1.6 and tensorboard1.6.
But still have the problem.
I wonder why it can run and get the address by Visual Studio tool, and why my port is not 6006.
Thank you.

**Comment by linmajia** [comment] 2018-08-08 07:29
@XUEZIJIAN , Tools for AI just launches TensorBoard using a random available port to avoid port confliction. The issue is that your TensorBoard in Anaconda is broken.

My suggestion is that you install Python from www.python.org, set it as the default Python environment in VS and install TensorFlow. You can refer [here](https://github.com/Microsoft/vs-tools-for-ai/blob/master/docs/prepare-localmachine.md#python)
